config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources:task
  get '/tasks', to: 'tasks#index'
  post '/tasks', to: 'tasks#create'
  get '/tasks/new', to: 'tasks#new'
  get '/tasks/:id', to: 'tasks#show', as: 'task' 
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  def show
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end
  def create
    @task = Task.create({ title: params['task']["title"], details: params['task']['details'] })
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/tasks/index.html.erb
<h1 class='mb-4'>My Tasks</h1>
<% @tasks.each do |item| %>
    <div class="d-flex border rounded w-50 shadow-sm m-2 pl-2 pt-2">
      <p class='pr-2'><%= check_box(item, :completed) %></p>
      <%= link_to "#{item.title}", task_path(item), class: "badge" %>    
     <p> - <%= item.completed %></p>
    </div>
<% end %>

<%# (class: 'back-btn' %>
<%# checkbox dynamic %>

app/views/tasks/new.html.erb
<h1 class='mb-4'>My Tasks</h1>

<%= form_for(@task, html: {class: 'form-group p-2'}) do |f| %>
  <%= f.label(:title) %>
  <%= f.text_field(:title, {class: 'form-control'}) %>
  <%= f.label(:details) %>
  <%= f.text_field(:details, {class: 'form-control'}) %>
  <%= f.submit({class: 'my-2par'}) %>
<% end %>

app/views/tasks/show.html.erb
<h1 class='mb-4 border-bottom'>Individual Task </h1>
    <h4 class="border w-50 bg-light p-1">
      <%= @task.title %>
    </h4>
    <p>
      <%= @task.details %>
      - <%= @task.completed %>
    </p>